title: Differenczi # your name (or website title) here
logo: "images/FlowersSprint2020.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist
  <br><br>
  Quantum mechanic
  <br><br>
  <a href="https://www.linkedin.com/in/agnesferenczi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
defaults:
  - scope:
      path: "images/spring2020"
    values:
      image: true